### PR TITLE
Add Universal Analytics & Refactor

### PR DESCRIPTION
**Pull request by gzog**
Added support for universal analytics and refactored code.

### CODE REVIEW

**Comment by tricknotes** [comment]
cool! It works for me :+1:

**Comment by danmaz74** [comment]
Thanks gzog - I just merged your request.

Sorry the slow response but I'm very busy with other projects at the moment.

**Comment by gzog** [comment]
No problem. Thanks for the merge

**Comment by danmaz74** [comment]
Thank you for the contribution!

**Pull request merged**
